import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { router } from '@/lib/roots-router'

const inter = Inter({ subsets: ['latin'], variable: "--font-sans" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const t = useTranslations('layout');
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}>
        <main className="flex flex-col justify-between h-[99svh]"><>{children}</>
          <footer className="flex gap-6 bg-black text-white p-6">
            <Link href={router.getHref('/imprint', { locale: "de" })}>{t("imprint")}</Link>
            <Link href={router.getHref('/data-privacy')}>{t("dataPrivacy")}</Link>
          </footer>
        </main>
      </body>
    </html>
  )
}
